name: Android CI (Build APK)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      # ВНИМАНИЕ: Если папка называется иначе, замените слово android на ваше имя папки
      working-directory: ./android 
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: ./android
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: |
          **/build/outputs/apk/debug/*.apk

